ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure("2") do |config|
  # config.vm.box_check_update = false

  config.vm.define :centos6_sg do |centos6_sg|
    centos6_sg.vm.provider "virtualbox" do |v|
          v.customize ["modifyvm", :id, "--name", "centos6_sg", "--memory", "2048"]
    end
    centos6_sg.vm.box = "geerlingguy/centos6"
    centos6_sg.vm.hostname = "shotgun"
    #centos6_sg.vm.network "public_network", bridge: 'en0: Wi-Fi (AirPort)', ip: "192.168.1.20" 
    centos6_sg.vm.network "private_network", ip: "192.168.2.20" 
    centos6_sg.vm.network :forwarded_port, guest: 22, host: 2200, id: "ssh"#, disabled: "true"
    centos6_sg.vm.network "forwarded_port", guest: 80, host: 5566
    #centos6_sg.vm.network "forwarded_port", guest: 8080, host: 9966
    centos6_sg.vm.provision "shell", path: "~/ShotgunPKG/sh/del.sh", privileged: true
    centos6_sg.vm.provision "file", source: "~/ShotgunPKG/sh/install_centos6.sh", destination: "$HOME/install_centos6.sh"
    centos6_sg.vm.provision "shell", path: "~/ShotgunPKG/sh/add_user.sh", privileged: true
  end
end
