$script_delete = <<SCRIPT
echo Deleting toolbox and sg folder ...
sudo rm -rf /home/vagrant/sg /home/vagrant/toolbox
SCRIPT

$script_chmod = <<SCRIPT
echo Deleting toolbox and sg folder ...
sudo chmod 777 -R /home/vagrant/sg
sudo chmod 777 -R /home/vagrant/toolbox
SCRIPT

ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure("2") do |config|
  # config.vm.box_check_update = false

  config.vm.define :centos7_empty do |centos7_empty|
    centos7_empty.vm.provider "virtualbox" do |v|
          v.customize ["modifyvm", :id, "--name", "centos7_empty", "--memory", "2048"]
    end
    centos7_empty.vm.box = "geerlingguy/centos7"
    centos7_empty.vm.hostname = "db"
    #centos7_empty.vm.network "public_network", bridge: 'en0: Wi-Fi (AirPort)', ip: "192.168.1.30" 
    centos7_empty.vm.network "private_network", ip: "192.168.2.80" 
    centos7_empty.vm.network :forwarded_port, guest: 22, host: 3100, id: "ssh"#, disabled: "true"
    centos7_empty.vm.network "forwarded_port", guest: 80, host: 8877
    centos7_empty.vm.network "forwarded_port", guest: 8080, host: 9977
    centos7_empty.vm.network "forwarded_port", guest: 5432, host: 7777
    #centos7_empty.vm.provision "shell", path: "./script/setup_vagrant.sh", privileged: true
    centos7_empty.vm.provision "shell",inline: $script_delete
    #centos7_empty.vm.provision "file", source: "~/ShotgunPKG", destination: "$HOME/sg"
    centos7_empty.vm.provision "file", source: "~/Git/enterprise-toolbox", destination: "$HOME/toolbox"
    centos7_empty.vm.provision "shell",inline: $script_chmod
  end
end
