$script = <<SCRIPT
echo Deleting toolbox and sg folder ...
rm -rf $HOME/sg $HOME/toolbox
SCRIPT

ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure("2") do |config|
  # config.vm.box_check_update = false

  config.vm.define :centos7_empty do |centos7_empty|
    centos7_empty.vm.provider "virtualbox" do |v|
          v.customize ["modifyvm", :id, "--name", "centos7_empty", "--memory", "2048"]
    end
    centos7_empty.vm.box = "geerlingguy/centos7"
    centos7_empty.vm.hostname = "shotgun"
    #centos7_empty.vm.network "public_network", bridge: 'en0: Wi-Fi (AirPort)', ip: "192.168.0.10" 
    centos7_empty.vm.network "forwarded_port", guest: 80, host: 8877
    centos7_empty.vm.network "forwarded_port", guest: 8080, host: 9977
    #centos7_empty.vm.provision "shell", path: "./script/setup_vagrant.sh", privileged: true
    centos7_empty.vm.provision "shell",inline: $script
    centos7_empty.vm.provision "file", source: "~/ShotgunPKG", destination: "$HOME/sg"
    centos7_empty.vm.provision "file", source: "~/Git/enterprise-toolbox", destination: "$HOME/toolbox"
  end
end
